### ISSUE TITLE
FEATURE REQUEST: Accept characters like : and -

### ISSUE THREAD

**Issue by williamli** [pmkary/comment-vscode#5]

**Comment by williamli** [comment]
I guess it might confuse the internal of the flagging and block building system...

**Comment by pmkary** [comment]
No actually that would be a really nice thing to have. I only limited the characters so that people be forced to write only names but I do agree some new characters must be there.

**Comment by williamli** [comment]
@pmkary thanks.

**Comment by pmkary** [comment]
`-`, `+`, `:`, `@`, `?`, and `!` are now supported
