### ISSUE TITLE
Add nix lang support

### ISSUE THREAD

**Issue by worldofpeace** [pmkary/comment-vscode#6]
The comments can be single-line, started with a # character, or inline/multi-line, enclosed within /* ... */.

**Comment by pmkary** [comment]
Yeah, I'm working on the standard to extend it well for languages like Python and Haskell that are indentation sensitive. For those languages this is gonna be added.

**Comment by worldofpeace** [comment]
Excellent! :+1:

**Comment by worldofpeace** [comment]
@pmkary So support for languages like python have been added here 5c796ae7d064f5b44e4c1a330ad428363c328c99 but I get the error 
```
Kary Comments can't be used in language nix
```

**Comment by pmkary** [comment]
Yeah that's because VS Code does not allow access to the language configuration info (or at least I have no idea if it's there) so each language has to be defined explicitly.

**Comment by pmkary** [comment]
Ah yeah. If you want any language supported, simply change [dictionary](https://github.com/pmkary/comment-vscode/blob/master/dictionary.js) to have it. And then make a PR. Thank you.
